import '../weather_api_openmeteo_sdk_generated.dart';

/// Daily enums provided by Open-Meteo. Storing all parameters available from documentation.
enum Daily {
  weather_code,
  temperature_2m_max,
  temperature_2m_min,
  apparent_temperature_max,
  apparent_temperature_min,
  sunrise,
  sunset,
  daylight_duration,
  sunshine_duration,
  uv_index_max,
  uv_index_clear_sky_max,
  precipitation_sum,
  rain_sum,
  showers_sum,
  snowfall_sum,
  precipitation_hours,
  precipitation_probability_max,
  precipitation_probability_min,
  precipitation_probability_mean,
  wind_speed_10m_max,
  wind_gusts_10m_max,
  wind_direction_10m_dominant,
  shortwave_radiation_sum,
  et0_fao_evapotranspiration,
  temperature_2m_mean,
  apparent_temperature_mean,
  wind_speed_10m_mean,
  cloud_cover_mean,
  relative_humidity_2m_mean,
  relative_humidity_2m_max,
  relative_humidity_2m_min,
  dew_point_2m_mean,
  dew_point_2m_min,
  dew_point_2m_max,
  pressure_msl_mean,
  soil_moisture_0_to_10cm_mean,
  et0_fao_evapotranspiration_sum,
  wave_height_max,
  wave_direction_dominant,
  wave_period_max,
  wind_wave_height_max,
  wind_wave_direction_dominant,
  wind_wave_period_max,
  wind_wave_peak_period_max,
  swell_wave_height_max,
  swell_wave_direction_dominant,
  swell_wave_period_max,
  swell_wave_peak_period_max,
  river_discharge,
  river_discharge_mean,
  river_discharge_median,
  river_discharge_max,
  river_discharge_min,
  river_discharge_p25,
  river_discharge_p75;

  static Daily? fromVariable(VariableWithValues v) => switch (v.variable) {
        Variable.precipitation_hours => Daily.precipitation_hours,
        Variable.weather_code => Daily.weather_code,
        Variable.sunrise => Daily.sunrise,
        Variable.sunset => Daily.sunset,
        Variable.sunshine_duration => Daily.sunshine_duration,
        Variable.daylight_duration => Daily.daylight_duration,
        Variable.et0_fao_evapotranspiration => Daily.et0_fao_evapotranspiration,
        Variable.temperature => switch (v.aggregation) {
            Aggregation.minimum => Daily.temperature_2m_min,
            Aggregation.maximum => Daily.temperature_2m_max,
            Aggregation.mean => Daily.temperature_2m_mean,
            _ => null,
          },
        Variable.apparent_temperature => switch (v.aggregation) {
            Aggregation.maximum => Daily.apparent_temperature_max,
            Aggregation.minimum => Daily.apparent_temperature_min,
            _ => null,
          },
        Variable.precipitation => Daily.precipitation_sum,
        Variable.rain => Daily.rain_sum,
        Variable.showers => Daily.showers_sum,
        Variable.snowfall => Daily.snowfall_sum,
        Variable.precipitation_probability => switch (v.aggregation) {
            Aggregation.maximum => Daily.precipitation_probability_max,
            Aggregation.minimum => Daily.precipitation_probability_min,
            Aggregation.mean => Daily.precipitation_probability_mean,
            _ => null,
          },
        Variable.wind_speed => switch (v.aggregation) {
            Aggregation.maximum => Daily.wind_speed_10m_max,
            Aggregation.mean => Daily.wind_speed_10m_mean,
            _ => null,
          },
        Variable.wind_gusts => Daily.wind_gusts_10m_max,
        Variable.wind_direction => Daily.wind_direction_10m_dominant,
        Variable.shortwave_radiation => Daily.shortwave_radiation_sum,
        Variable.uv_index => Daily.uv_index_max,
        Variable.uv_index_clear_sky => Daily.uv_index_clear_sky_max,
        Variable.cloud_cover => Daily.cloud_cover_mean,
        Variable.relative_humidity => switch (v.aggregation) {
            Aggregation.maximum => Daily.relative_humidity_2m_max,
            Aggregation.minimum => Daily.relative_humidity_2m_min,
            Aggregation.mean => Daily.relative_humidity_2m_mean,
            _ => null,
          },
        Variable.soil_moisture => Daily.soil_moisture_0_to_10cm_mean,
        Variable.pressure_msl => Daily.pressure_msl_mean,
        Variable.wave_height => Daily.wave_height_max,
        Variable.wind_wave_height => Daily.wind_wave_height_max,
        Variable.swell_wave_height => Daily.swell_wave_height_max,
        Variable.wave_direction => Daily.wave_direction_dominant,
        Variable.wind_wave_direction => Daily.wind_wave_direction_dominant,
        Variable.swell_wave_direction => Daily.swell_wave_direction_dominant,
        Variable.wave_period => Daily.wave_period_max,
        Variable.wind_wave_period => Daily.wind_wave_period_max,
        Variable.swell_wave_period => Daily.swell_wave_period_max,
        Variable.wind_wave_peak_period => Daily.wind_wave_peak_period_max,
        Variable.swell_wave_peak_period => Daily.swell_wave_peak_period_max,
        Variable.river_discharge => switch (v.aggregation) {
            Aggregation.none => Daily.river_discharge,
            Aggregation.maximum => Daily.river_discharge_max,
            Aggregation.minimum => Daily.river_discharge_min,
            Aggregation.mean => Daily.river_discharge_mean,
            Aggregation.median => Daily.river_discharge_median,
            Aggregation.p25 => Daily.river_discharge_p25,
            Aggregation.p75 => Daily.river_discharge_p75,
            _ => null,
          },
        _ => null,
      };
}
